networks:
  ? moirai_network
services:
  postgresql:
    restart: always
    container_name: postgresql
    hostname: postgresql
    image: postgres:18-alpine
    networks:
      - moirai_network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: moirai
      POSTGRES_PASSWORD: moirai
      POSTGRES_DB: moirai
  qdrant:
    restart: always
    container_name: qdrant
    hostname: qdrant
    image: qdrant/qdrant:v1.17.1
    networks:
      - moirai_network
    ports:
      - "6333:6333"
      - "6334:6334"